config/routes.rb
FlickrLab::Application.routes.draw do
  get "sessions/new"
  get "users/new"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :photos
  resources :users
  resources :sessions

  resources :albums

  root :to => "home#index"
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ActiveRecord::Base
  attr_accessible :name

  has_many :photos
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Photo < ActiveRecord::Base
  attr_accessible :image, :name, :album_id

  belongs_to :album

  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  attr_accessible :username, :email, :password, :password_confirmation

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    login(params[:username], params[:email], params[:remember_me])
    if @user
      redirect_back_or_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "username, email or password invalid :("
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <tr>
    <th>Name:</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= album.name %></td>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @album.name %></h1>

<% @album.photos.each do |photo| %>
<div class=""><%= image_tag photo.image %></div>

<% end %>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlickrLab</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="brand" href="./index.html">Flickr</a>
            <div class="nav-collapse collapse">
              <ul class="nav">
                <li class="">
                  <% if @current_user != nil %>
                    logged in as <%= @current_user.username %>
                    <%= link_to "Log out", logout_path %>
                  <% else %>
                    <%= link_to "Sign up", signup_path %>
                    <%= link_to "Log in", login_path %>
                  <% end %>
                </li>
                <li class="">
                  <a href="/albums">Albums</a>
                </li>
                <li class="">
                  <a href="/photos">Photos</a>
                </li>
                <li class="">
                  <a href="/albums/new">New Album</a>
                </li>
                <li class="">
                  <a href="/photos/new">New Photo</a>
                </li>
                <li class="">
                  <a href="#">Login</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

  <div class="jumbotron masthead">
    <div class="container">
      <h1>Flickr</h1>

    </div>
  </div>
<div class="container">
  <div class="marketing">
    <div class="row-fluid">
      <div class="span10">
        <div class="span4">
          <% flash.each do |name, msg| %>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          <% end %>
        </div>
        <%= yield %>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>My photos</h1>
<%= link_to 'New Photo', new_photo_path %>

<% @photos.each do |photo| %>

    <div><%= photo.name %></div>
    <div><%= image_tag photo.image %></div>
    <div><%= link_to 'Show', photo %></div>
    <div><%= link_to 'Edit', edit_photo_path(photo) %></div>
    <div><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></div>

<% end %>

</div>

<br>

app/views/photos/new.html.erb
<div class="offset3 hero-unit span6 offset3">
<h1>New Photo</h1>
<hr class="soften">
<%= form_for(@photo, :html_options => {:multipart => true}) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :album_id %>
    <%= f.collection_select(:album_id, Album.all, :id, :name, {:prompt => "select album"}) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="span4"></div>
<%= @photo.name %>
<%= image_tag @photo.image %>
<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>
</div>

app/views/users/new.html.erb
<div class="offset3 hero-unit span6 offset3">

<%= form_for @user do |f| %>
<h1>Sign Up!</h1>

<div class="field">
<%= f.label :username %>
<%= f.text_field :username %>
</div>

<div class="field">
<%= f.label :email %>
<%= f.text_field :email %>
</div>

<div class="field">
<%= f.label :password %>
<%= f.text_field :password %>
</div>

<div class="field">
<%= f.label :password_confirmation %>
<%= f.text_field :password_confirmation %>
</div>

<div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>
</div>
</div>
</div>